### ISSUE TITLE
Ludwig messing with WoW nick autocomplete

### ISSUE THREAD

**Issue by jjnilton** [tullamods/Ludwig#15]
When trying to autocomplete a name, the rest of the name is not replaced when I keep typing:

https://dl.dropboxusercontent.com/u/20240539/2013-11-27_01-03-25.gif

**Comment by boktai1000** [comment]
This issue is still present even now in BC Classic, where when I try to type /friend followed by a name, I can't - because Ludwig is autocompleted it for me and there's nothing I can do about it.

**Comment by repsejnworb** [comment]
Breaking issue tbh, any chance of having this looked at?

**Comment by xizar** [comment]
This issue is still present in wow 9.2.7 when attempting to send /whispers and /tells.

If this issue cannot be fixed, can we get a toggle to disable autocomplete?  The searchable database is valuable by itself and while the command-line interface is useful, it does not merit interfering with more commonly used functions of the game.

**Comment by Jaliborc** [comment]
I'll change how the slash autocomplete works entirely as to not interfere any more
