### ISSUE TITLE
Classic Version

### ISSUE THREAD

**Issue by inferno771** [tullamods/Ludwig#18]
Will there be a classic version of this mod?

**Comment by Jaliborc** [comment]
Yes. Currently busy getting all the other mods to a point I'm satisfied with. Ludwig will require a complete rewrite of the DB generation process, because blizzard changed their entire API.

**Comment by Jaliborc** [comment]
So it will take a while.

**Comment by apazzolini** [comment]
Is the new API documented somewhere?

**Comment by Mdrg00** [comment]
Can't wait to use this wonderful addon once again! I have used it for all sorts of purposes, not just to spam trade channel, for example. During a conversation you may want to link a world drop to provide either proof that it exists, or to show its stats. Or perhaps to filter it out to show helms, so you can find the best one with the stats you need - thats also the right "look" you want, since classic doesnt have Transmog... Also so many times I have looked up profession recipies to check what it takes to create an item, so I could start farming the mats. (too lazy to alt-tab) :stuck_out_tongue:

**Comment by amanalar** [comment]
I also can't wait :D
