### ISSUE TITLE
[[ not working 

### ISSUE THREAD

**Issue by bbleeker** [tullamods/Ludwig#29]
Typing [[Item Name] in chat doesn't work for me :(

**Comment by Zautix** [comment]
Same. This is with no other addons enabled at all.

**Comment by honorgog** [comment]
Thought this was caused by another addon but seems it's internal to Ludwig.  Disabling all addons except for Ludwig still doesn't allow for a link to appear in a chat.  Try it.  Go to trade and try to get "Anguished Ale" to appear in a price query.  That's a rather obscure gray item that is no longer useful in game.  Won't echo when you hit [RETURN].  Someone stated that you have to have an item in your inventory to get it to echo but that's not true.  People ask for things they don't have with a link in trade all the time.

**Comment by boktai1000** [comment]
This is still occurring in Classic Season of Discovery as of 12/04/2023 - I also think there is a problem with /lw but might be worth opening a separate bug report for that 

![image](https://github.com/tullamods/Ludwig/assets/9054563/14b0e3f5-1ac7-428d-b2bd-3440d20653a2)

![image](https://github.com/tullamods/Ludwig/assets/9054563/bc545236-c960-46c4-9370-e0bf41511e15)

**Comment by Jaliborc** [comment]
The command has changed to lw:YOUR ITEM HERE
